version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: debt_manager_postgres
    environment:
      POSTGRES_DB: debt_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: